namespace VehIC_WF.Search
{
    using DevExpress.Utils;
    using DevExpress.XtraTreeList;
    using DevExpress.XtraTreeList.Columns;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class FC_Search_Task : UserControl
    {
        private Button btn_task_cancel;
        private Button btn_task_terminal;
        private CheckBox cb_th;
        private CheckBox chbox_needweigh;
        private IContainer components = null;
        private GroupBox groupBox3;
        private Label label11;
        private Label label12;
        private Label label14;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label8;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private RadioButton rb_wzlx_in;
        private RadioButton rb_wzlx_out;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private TabPage tabPage3;
        private TreeList tl_BillItem;
        private TreeList tl_door_limite;
        private TreeList tl_taskflow;
        private TreeListColumn tlc1;
        private TreeListColumn tlc10;
        private TreeListColumn tlc11;
        private TreeListColumn tlc12;
        private TreeListColumn tlc13;
        private TreeListColumn tlc2;
        private TreeListColumn tlc3;
        private TreeListColumn tlc4;
        private TreeListColumn tlc5;
        private TreeListColumn tlc6;
        private TreeListColumn tlc7;
        private TreeListColumn tlc8;
        private TreeListColumn tlc9;
        private TreeListColumn treeListColumn1;
        private TreeListColumn treeListColumn19;
        private TreeListColumn treeListColumn2;
        private TreeListColumn treeListColumn20;
        private TreeListColumn treeListColumn21;
        private TreeListColumn treeListColumn3;
        private TreeListColumn treeListColumn4;
        private TreeListColumn treeListColumn5;
        private TreeListColumn treeListColumn6;
        private TreeListColumn treeListColumn7;
        private TreeListColumn treeListColumn8;
        private TextBox txt_billno;
        private TextBox txt_billstatus;
        private TextBox txt_billtype;
        private TextBox txt_fkr;
        private TextBox txt_fksj;
        private TextBox txt_remark;

        public FC_Search_Task()
        {
            this.InitializeComponent();
        }

        private void btn_print_Click(object sender, EventArgs e)
        {
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FC_Search_Task));
            this.panel1 = new Panel();
            this.label8 = new Label();
            this.panel2 = new Panel();
            this.txt_remark = new TextBox();
            this.label5 = new Label();
            this.cb_th = new CheckBox();
            this.panel3 = new Panel();
            this.btn_task_terminal = new Button();
            this.btn_task_cancel = new Button();
            this.txt_fksj = new TextBox();
            this.groupBox3 = new GroupBox();
            this.rb_wzlx_out = new RadioButton();
            this.rb_wzlx_in = new RadioButton();
            this.txt_billstatus = new TextBox();
            this.label4 = new Label();
            this.label2 = new Label();
            this.txt_fkr = new TextBox();
            this.label3 = new Label();
            this.chbox_needweigh = new CheckBox();
            this.txt_billtype = new TextBox();
            this.label14 = new Label();
            this.label11 = new Label();
            this.txt_billno = new TextBox();
            this.label12 = new Label();
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.tl_BillItem = new TreeList();
            this.tlc1 = new TreeListColumn();
            this.tlc2 = new TreeListColumn();
            this.tlc3 = new TreeListColumn();
            this.tlc4 = new TreeListColumn();
            this.tlc5 = new TreeListColumn();
            this.tlc6 = new TreeListColumn();
            this.tlc7 = new TreeListColumn();
            this.tlc8 = new TreeListColumn();
            this.tlc9 = new TreeListColumn();
            this.tlc10 = new TreeListColumn();
            this.tlc11 = new TreeListColumn();
            this.tlc12 = new TreeListColumn();
            this.tlc13 = new TreeListColumn();
            this.tabPage2 = new TabPage();
            this.tl_taskflow = new TreeList();
            this.treeListColumn1 = new TreeListColumn();
            this.treeListColumn2 = new TreeListColumn();
            this.treeListColumn3 = new TreeListColumn();
            this.treeListColumn4 = new TreeListColumn();
            this.treeListColumn5 = new TreeListColumn();
            this.treeListColumn6 = new TreeListColumn();
            this.treeListColumn7 = new TreeListColumn();
            this.treeListColumn8 = new TreeListColumn();
            this.tabPage3 = new TabPage();
            this.tl_door_limite = new TreeList();
            this.treeListColumn19 = new TreeListColumn();
            this.treeListColumn20 = new TreeListColumn();
            this.treeListColumn21 = new TreeListColumn();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tl_BillItem.BeginInit();
            this.tabPage2.SuspendLayout();
            this.tl_taskflow.BeginInit();
            this.tabPage3.SuspendLayout();
            this.tl_door_limite.BeginInit();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.label8);
            this.panel1.Dock = DockStyle.Top;
            this.panel1.Location = new Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x3fc, 0x24);
            this.panel1.TabIndex = 1;
            this.label8.BackColor = Color.Transparent;
            this.label8.Dock = DockStyle.Fill;
            this.label8.Font = new System.Drawing.Font("宋体", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label8.ForeColor = Color.Blue;
            this.label8.Location = new Point(0, 0);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x3fc, 0x24);
            this.label8.TabIndex = 3;
            this.label8.Text = "磁卡作业单";
            this.label8.TextAlign = ContentAlignment.MiddleCenter;
            this.panel2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel2.Controls.Add(this.txt_remark);
            this.panel2.Controls.Add(this.label5);
            this.panel2.Controls.Add(this.cb_th);
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Controls.Add(this.txt_fksj);
            this.panel2.Controls.Add(this.groupBox3);
            this.panel2.Controls.Add(this.txt_billstatus);
            this.panel2.Controls.Add(this.label4);
            this.panel2.Controls.Add(this.label2);
            this.panel2.Controls.Add(this.txt_fkr);
            this.panel2.Controls.Add(this.label3);
            this.panel2.Controls.Add(this.chbox_needweigh);
            this.panel2.Controls.Add(this.txt_billtype);
            this.panel2.Controls.Add(this.label14);
            this.panel2.Controls.Add(this.label11);
            this.panel2.Controls.Add(this.txt_billno);
            this.panel2.Controls.Add(this.label12);
            this.panel2.Dock = DockStyle.Top;
            this.panel2.Location = new Point(0, 0x24);
            this.panel2.Margin = new Padding(4);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(0x3fc, 140);
            this.panel2.TabIndex = 0xc0;
            this.txt_remark.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_remark.Location = new Point(0x4c, 0x55);
            this.txt_remark.Margin = new Padding(4);
            this.txt_remark.Multiline = true;
            this.txt_remark.Name = "txt_remark";
            this.txt_remark.ReadOnly = true;
            this.txt_remark.Size = new Size(0x309, 0x2a);
            this.txt_remark.TabIndex = 0xdd;
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label5.Location = new Point(0x2b, 0x58);
            this.label5.Margin = new Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x23, 14);
            this.label5.TabIndex = 220;
            this.label5.Text = "说明";
            this.cb_th.AutoSize = true;
            this.cb_th.Enabled = false;
            this.cb_th.Font = new System.Drawing.Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cb_th.Location = new Point(0x2c5, 0x34);
            this.cb_th.Name = "cb_th";
            this.cb_th.Size = new Size(0x5b, 20);
            this.cb_th.TabIndex = 0xd5;
            this.cb_th.Text = "是否退货";
            this.cb_th.UseVisualStyleBackColor = true;
            this.panel3.Controls.Add(this.btn_task_terminal);
            this.panel3.Controls.Add(this.btn_task_cancel);
            this.panel3.Dock = DockStyle.Right;
            this.panel3.Location = new Point(860, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(0x9e, 0x8a);
            this.panel3.TabIndex = 0xb7;
            this.btn_task_terminal.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.btn_task_terminal.Location = new Point(0x16, 0x49);
            this.btn_task_terminal.Name = "btn_task_terminal";
            this.btn_task_terminal.Size = new Size(0x74, 0x2c);
            this.btn_task_terminal.TabIndex = 0xd5;
            this.btn_task_terminal.Text = "终止作业";
            this.btn_task_terminal.UseVisualStyleBackColor = true;
            this.btn_task_cancel.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.btn_task_cancel.Location = new Point(0x16, 0x10);
            this.btn_task_cancel.Name = "btn_task_cancel";
            this.btn_task_cancel.Size = new Size(0x74, 0x2c);
            this.btn_task_cancel.TabIndex = 0x90;
            this.btn_task_cancel.Text = "撤 销";
            this.btn_task_cancel.UseVisualStyleBackColor = true;
            this.txt_fksj.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_fksj.Location = new Point(0x2c5, 13);
            this.txt_fksj.Margin = new Padding(4);
            this.txt_fksj.Name = "txt_fksj";
            this.txt_fksj.ReadOnly = true;
            this.txt_fksj.Size = new Size(0x90, 0x17);
            this.txt_fksj.TabIndex = 0xb3;
            this.txt_fksj.TextAlign = HorizontalAlignment.Right;
            this.groupBox3.Controls.Add(this.rb_wzlx_out);
            this.groupBox3.Controls.Add(this.rb_wzlx_in);
            this.groupBox3.Location = new Point(0x11f, 40);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x90, 0x21);
            this.groupBox3.TabIndex = 0xb6;
            this.groupBox3.TabStop = false;
            this.rb_wzlx_out.AutoSize = true;
            this.rb_wzlx_out.Enabled = false;
            this.rb_wzlx_out.Font = new System.Drawing.Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rb_wzlx_out.Location = new Point(0x51, 11);
            this.rb_wzlx_out.Name = "rb_wzlx_out";
            this.rb_wzlx_out.Size = new Size(0x3a, 20);
            this.rb_wzlx_out.TabIndex = 0xaf;
            this.rb_wzlx_out.Text = "出厂";
            this.rb_wzlx_out.UseVisualStyleBackColor = true;
            this.rb_wzlx_in.AutoSize = true;
            this.rb_wzlx_in.Checked = true;
            this.rb_wzlx_in.Enabled = false;
            this.rb_wzlx_in.Font = new System.Drawing.Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rb_wzlx_in.Location = new Point(11, 10);
            this.rb_wzlx_in.Name = "rb_wzlx_in";
            this.rb_wzlx_in.Size = new Size(0x3a, 20);
            this.rb_wzlx_in.TabIndex = 0xae;
            this.rb_wzlx_in.TabStop = true;
            this.rb_wzlx_in.Text = "入厂";
            this.rb_wzlx_in.UseVisualStyleBackColor = true;
            this.txt_billstatus.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_billstatus.Location = new Point(0x11f, 13);
            this.txt_billstatus.Margin = new Padding(4);
            this.txt_billstatus.Name = "txt_billstatus";
            this.txt_billstatus.ReadOnly = true;
            this.txt_billstatus.Size = new Size(0x90, 0x17);
            this.txt_billstatus.TabIndex = 0xb5;
            this.txt_billstatus.TextAlign = HorizontalAlignment.Right;
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label4.Location = new Point(0xe3, 0x11);
            this.label4.Margin = new Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x3f, 14);
            this.label4.TabIndex = 180;
            this.label4.Text = "单据状态";
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label2.Location = new Point(0x289, 0x12);
            this.label2.Margin = new Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x3f, 14);
            this.label2.TabIndex = 0xb2;
            this.label2.Text = "发卡时间";
            this.txt_fkr.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_fkr.Location = new Point(0x1f2, 13);
            this.txt_fkr.Margin = new Padding(4);
            this.txt_fkr.Name = "txt_fkr";
            this.txt_fkr.ReadOnly = true;
            this.txt_fkr.Size = new Size(0x90, 0x17);
            this.txt_fkr.TabIndex = 0xb1;
            this.txt_fkr.TextAlign = HorizontalAlignment.Right;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label3.Location = new Point(0x1c3, 0x11);
            this.label3.Margin = new Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x31, 14);
            this.label3.TabIndex = 0xb0;
            this.label3.Text = "发卡人";
            this.chbox_needweigh.AutoSize = true;
            this.chbox_needweigh.Enabled = false;
            this.chbox_needweigh.Font = new System.Drawing.Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.chbox_needweigh.Location = new Point(0x1f2, 0x35);
            this.chbox_needweigh.Name = "chbox_needweigh";
            this.chbox_needweigh.Size = new Size(0x3b, 20);
            this.chbox_needweigh.TabIndex = 0xaf;
            this.chbox_needweigh.Text = "计重";
            this.chbox_needweigh.UseVisualStyleBackColor = true;
            this.txt_billtype.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_billtype.Location = new Point(0x4c, 50);
            this.txt_billtype.Margin = new Padding(4);
            this.txt_billtype.Name = "txt_billtype";
            this.txt_billtype.ReadOnly = true;
            this.txt_billtype.Size = new Size(0x90, 0x17);
            this.txt_billtype.TabIndex = 0x97;
            this.txt_billtype.TextAlign = HorizontalAlignment.Right;
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label14.Location = new Point(15, 0x36);
            this.label14.Margin = new Padding(4, 0, 4, 0);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x3f, 14);
            this.label14.TabIndex = 150;
            this.label14.Text = "业务类型";
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label11.Location = new Point(0xe3, 0x35);
            this.label11.Margin = new Padding(4, 0, 4, 0);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x3f, 14);
            this.label11.TabIndex = 0x94;
            this.label11.Text = "物资流向";
            this.txt_billno.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.txt_billno.Location = new Point(0x4c, 13);
            this.txt_billno.Margin = new Padding(4);
            this.txt_billno.Name = "txt_billno";
            this.txt_billno.ReadOnly = true;
            this.txt_billno.Size = new Size(0x90, 0x17);
            this.txt_billno.TabIndex = 0x93;
            this.txt_billno.TextAlign = HorizontalAlignment.Right;
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label12.Location = new Point(15, 0x11);
            this.label12.Margin = new Padding(4, 0, 4, 0);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x3f, 14);
            this.label12.TabIndex = 0x92;
            this.label12.Text = "作业单号";
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Dock = DockStyle.Fill;
            this.tabControl1.Location = new Point(0, 0xb0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x3fc, 0x125);
            this.tabControl1.TabIndex = 0xc1;
            this.tabPage1.Controls.Add(this.tl_BillItem);
            this.tabPage1.Location = new Point(4, 0x17);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(0x3f4, 0x10a);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "物资明细";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tl_BillItem.BackgroundImage = (Image) resources.GetObject("tl_BillItem.BackgroundImage");
            this.tl_BillItem.Columns.AddRange(new TreeListColumn[] { this.tlc1, this.tlc2, this.tlc3, this.tlc4, this.tlc5, this.tlc6, this.tlc7, this.tlc8, this.tlc9, this.tlc10, this.tlc11, this.tlc12, this.tlc13 });
            this.tl_BillItem.Dock = DockStyle.Fill;
            this.tl_BillItem.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.tl_BillItem.HorzScrollVisibility = ScrollVisibility.Always;
            this.tl_BillItem.Location = new Point(3, 3);
            this.tl_BillItem.Name = "tl_BillItem";
            this.tl_BillItem.OptionsView.AutoWidth = false;
            this.tl_BillItem.OptionsView.ShowFocusedFrame = false;
            this.tl_BillItem.Size = new Size(0x3ee, 260);
            this.tl_BillItem.TabIndex = 0xc0;
            this.tl_BillItem.TreeLevelWidth = 12;
            this.tlc1.Caption = "行号";
            this.tlc1.FieldName = "行号";
            this.tlc1.MinWidth = 100;
            this.tlc1.Name = "tlc1";
            this.tlc1.OptionsColumn.AllowEdit = false;
            this.tlc1.OptionsColumn.AllowMove = false;
            this.tlc1.OptionsColumn.AllowSort = false;
            this.tlc1.OptionsColumn.FixedWidth = true;
            this.tlc1.OptionsColumn.ReadOnly = true;
            this.tlc1.OptionsColumn.ShowInCustomizationForm = false;
            this.tlc1.VisibleIndex = 0;
            this.tlc1.Width = 100;
            this.tlc2.Caption = "存货编码";
            this.tlc2.FieldName = "存货编码";
            this.tlc2.Name = "tlc2";
            this.tlc2.OptionsColumn.AllowEdit = false;
            this.tlc2.OptionsColumn.AllowMove = false;
            this.tlc2.OptionsColumn.AllowSort = false;
            this.tlc2.OptionsColumn.ReadOnly = true;
            this.tlc2.VisibleIndex = 1;
            this.tlc2.Width = 120;
            this.tlc3.Caption = "存货名称";
            this.tlc3.FieldName = "存货名称";
            this.tlc3.Name = "tlc3";
            this.tlc3.OptionsColumn.AllowEdit = false;
            this.tlc3.OptionsColumn.AllowMove = false;
            this.tlc3.OptionsColumn.AllowSort = false;
            this.tlc3.VisibleIndex = 2;
            this.tlc3.Width = 120;
            this.tlc4.Caption = "型号规格图号";
            this.tlc4.FieldName = "型号规格图号";
            this.tlc4.Name = "tlc4";
            this.tlc4.OptionsColumn.AllowEdit = false;
            this.tlc4.OptionsColumn.AllowMove = false;
            this.tlc4.OptionsColumn.AllowSort = false;
            this.tlc4.VisibleIndex = 3;
            this.tlc4.Width = 100;
            this.tlc5.Caption = "计量单位";
            this.tlc5.FieldName = "计量单位";
            this.tlc5.Name = "tlc5";
            this.tlc5.OptionsColumn.AllowEdit = false;
            this.tlc5.OptionsColumn.AllowMove = false;
            this.tlc5.OptionsColumn.AllowSort = false;
            this.tlc5.VisibleIndex = 4;
            this.tlc6.Caption = "数量";
            this.tlc6.FieldName = "数量";
            this.tlc6.Name = "tlc6";
            this.tlc6.OptionsColumn.AllowEdit = false;
            this.tlc6.OptionsColumn.AllowMove = false;
            this.tlc6.OptionsColumn.AllowSort = false;
            this.tlc6.VisibleIndex = 5;
            this.tlc7.Caption = "辅数量";
            this.tlc7.FieldName = "实际数量";
            this.tlc7.Name = "tlc7";
            this.tlc7.VisibleIndex = 6;
            this.tlc8.Caption = "实际数量";
            this.tlc8.FieldName = "实际数量";
            this.tlc8.Name = "tlc8";
            this.tlc8.VisibleIndex = 7;
            this.tlc9.Caption = "实际辅数量";
            this.tlc9.FieldName = "实际辅数量";
            this.tlc9.Name = "tlc9";
            this.tlc9.VisibleIndex = 8;
            this.tlc10.Caption = "状态";
            this.tlc10.FieldName = "状态";
            this.tlc10.Name = "tlc10";
            this.tlc10.VisibleIndex = 9;
            this.tlc11.Caption = "备注";
            this.tlc11.FieldName = "备注";
            this.tlc11.Name = "tlc11";
            this.tlc11.VisibleIndex = 10;
            this.tlc11.Width = 100;
            this.tlc12.Caption = "客商/业务单位";
            this.tlc12.FieldName = "客商/业务单位";
            this.tlc12.Name = "tlc12";
            this.tlc12.VisibleIndex = 11;
            this.tlc12.Width = 170;
            this.tlc13.Caption = "单据号";
            this.tlc13.FieldName = "单据号";
            this.tlc13.Name = "tlc13";
            this.tlc13.VisibleIndex = 12;
            this.tlc13.Width = 170;
            this.tabPage2.Controls.Add(this.tl_taskflow);
            this.tabPage2.Location = new Point(4, 0x17);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x3f4, 0x10a);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "实际路线";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.tl_taskflow.BackgroundImage = (Image) resources.GetObject("tl_taskflow.BackgroundImage");
            this.tl_taskflow.Columns.AddRange(new TreeListColumn[] { this.treeListColumn1, this.treeListColumn2, this.treeListColumn3, this.treeListColumn4, this.treeListColumn5, this.treeListColumn6, this.treeListColumn7, this.treeListColumn8 });
            this.tl_taskflow.Dock = DockStyle.Fill;
            this.tl_taskflow.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.tl_taskflow.Location = new Point(3, 3);
            this.tl_taskflow.Name = "tl_taskflow";
            this.tl_taskflow.OptionsView.ShowFocusedFrame = false;
            this.tl_taskflow.Size = new Size(0x3ee, 260);
            this.tl_taskflow.TabIndex = 9;
            this.tl_taskflow.TreeLevelWidth = 12;
            this.treeListColumn1.AppearanceCell.BorderColor = Color.Red;
            this.treeListColumn1.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn1.AppearanceCell.Options.UseBorderColor = true;
            this.treeListColumn1.AppearanceCell.Options.UseFont = true;
            this.treeListColumn1.AppearanceCell.Options.UseTextOptions = true;
            this.treeListColumn1.AppearanceCell.TextOptions.HAlignment = HorzAlignment.Near;
            this.treeListColumn1.Caption = "序号";
            this.treeListColumn1.FieldName = "状态";
            this.treeListColumn1.MinWidth = 10;
            this.treeListColumn1.Name = "treeListColumn1";
            this.treeListColumn1.OptionsColumn.AllowEdit = false;
            this.treeListColumn1.OptionsColumn.AllowSize = false;
            this.treeListColumn1.OptionsColumn.FixedWidth = true;
            this.treeListColumn1.VisibleIndex = 0;
            this.treeListColumn1.Width = 0x2d;
            this.treeListColumn2.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn2.AppearanceCell.Options.UseFont = true;
            this.treeListColumn2.Caption = "作业类型";
            this.treeListColumn2.FieldName = "作业类型";
            this.treeListColumn2.Name = "treeListColumn2";
            this.treeListColumn2.OptionsColumn.AllowSize = false;
            this.treeListColumn2.VisibleIndex = 1;
            this.treeListColumn2.Width = 0x19;
            this.treeListColumn3.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn3.AppearanceCell.Options.UseFont = true;
            this.treeListColumn3.Caption = "作业点名称";
            this.treeListColumn3.FieldName = "作业点名称";
            this.treeListColumn3.Name = "treeListColumn3";
            this.treeListColumn3.VisibleIndex = 2;
            this.treeListColumn3.Width = 60;
            this.treeListColumn4.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn4.AppearanceCell.Options.UseFont = true;
            this.treeListColumn4.Caption = "作业结果";
            this.treeListColumn4.FieldName = "作业结果";
            this.treeListColumn4.Name = "treeListColumn4";
            this.treeListColumn4.OptionsColumn.AllowEdit = false;
            this.treeListColumn4.OptionsColumn.AllowMove = false;
            this.treeListColumn4.OptionsColumn.AllowMoveToCustomizationForm = false;
            this.treeListColumn4.OptionsColumn.AllowSort = false;
            this.treeListColumn4.OptionsColumn.ShowInCustomizationForm = false;
            this.treeListColumn4.VisibleIndex = 3;
            this.treeListColumn4.Width = 60;
            this.treeListColumn5.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn5.AppearanceCell.Options.UseFont = true;
            this.treeListColumn5.Caption = "作业人";
            this.treeListColumn5.FieldName = "作业人";
            this.treeListColumn5.Name = "treeListColumn5";
            this.treeListColumn5.OptionsColumn.FixedWidth = true;
            this.treeListColumn5.VisibleIndex = 4;
            this.treeListColumn5.Width = 0x37;
            this.treeListColumn6.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn6.AppearanceCell.Options.UseFont = true;
            this.treeListColumn6.Caption = "开始时间";
            this.treeListColumn6.FieldName = "开始时间";
            this.treeListColumn6.Name = "treeListColumn6";
            this.treeListColumn6.VisibleIndex = 5;
            this.treeListColumn6.Width = 100;
            this.treeListColumn7.AppearanceCell.Font = new System.Drawing.Font("Tahoma", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.treeListColumn7.AppearanceCell.Options.UseFont = true;
            this.treeListColumn7.Caption = "结束时间";
            this.treeListColumn7.FieldName = "结束时间";
            this.treeListColumn7.Name = "treeListColumn7";
            this.treeListColumn7.VisibleIndex = 6;
            this.treeListColumn7.Width = 100;
            this.treeListColumn8.Caption = "状态";
            this.treeListColumn8.FieldName = "状态";
            this.treeListColumn8.Name = "treeListColumn8";
            this.treeListColumn8.VisibleIndex = 7;
            this.tabPage3.Controls.Add(this.tl_door_limite);
            this.tabPage3.Location = new Point(4, 0x17);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new Padding(3);
            this.tabPage3.Size = new Size(0x3f4, 0x10a);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "进出门限制";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.tl_door_limite.BackgroundImage = (Image) resources.GetObject("tl_door_limite.BackgroundImage");
            this.tl_door_limite.Columns.AddRange(new TreeListColumn[] { this.treeListColumn19, this.treeListColumn20, this.treeListColumn21 });
            this.tl_door_limite.Dock = DockStyle.Fill;
            this.tl_door_limite.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.tl_door_limite.Location = new Point(3, 3);
            this.tl_door_limite.Name = "tl_door_limite";
            this.tl_door_limite.OptionsView.AutoWidth = false;
            this.tl_door_limite.OptionsView.ShowFocusedFrame = false;
            this.tl_door_limite.Size = new Size(0x3ee, 260);
            this.tl_door_limite.TabIndex = 12;
            this.tl_door_limite.TreeLevelWidth = 12;
            this.treeListColumn19.Caption = "进出门";
            this.treeListColumn19.FieldName = "进出门";
            this.treeListColumn19.MinWidth = 100;
            this.treeListColumn19.Name = "treeListColumn19";
            this.treeListColumn19.VisibleIndex = 0;
            this.treeListColumn19.Width = 90;
            this.treeListColumn20.Caption = "门岗编码";
            this.treeListColumn20.FieldName = "门岗编码";
            this.treeListColumn20.Name = "treeListColumn20";
            this.treeListColumn20.VisibleIndex = 1;
            this.treeListColumn20.Width = 100;
            this.treeListColumn21.Caption = "门岗名称";
            this.treeListColumn21.FieldName = "门岗名称";
            this.treeListColumn21.Name = "treeListColumn21";
            this.treeListColumn21.VisibleIndex = 2;
            this.treeListColumn21.Width = 150;
            base.AutoScaleDimensions = new SizeF(7f, 14f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.tabControl1);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            this.Font = new System.Drawing.Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            base.Name = "FC_Search_Task";
            base.Size = new Size(0x3fc, 0x1d5);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tl_BillItem.EndInit();
            this.tabPage2.ResumeLayout(false);
            this.tl_taskflow.EndInit();
            this.tabPage3.ResumeLayout(false);
            this.tl_door_limite.EndInit();
            base.ResumeLayout(false);
        }
    }
}

